import { Exercise } from './types.ts';

export const challengeExercises: Exercise[] = [
  {
    id: 'challenge-fix-typo',
    title: 'Fix the Typo',
    description: 'Find and fix the typo in the word "recieve".',
    initialBuffer: ['function recieve(data) {', '  return data;', '}'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['function receive(data) {', '  return data;', '}'],
    hints: ['Navigate to the typo and use r to replace', 'Or use f to find, then x to delete extra char'],
    optimalKeystrokes: 4, // frixi or similar
    category: 'challenge',
    difficulty: 'beginner',
  },
  {
    id: 'challenge-delete-comment',
    title: 'Delete the Comment',
    description: 'Remove the comment from the end of the line.',
    initialBuffer: ['const MAX = 100; // TODO: make configurable'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['const MAX = 100;'],
    hints: ['Navigate to the comment start and use D', 'Try f/ then D'],
    optimalKeystrokes: 4, // f/hD or f D
    category: 'challenge',
    difficulty: 'beginner',
  },
  {
    id: 'challenge-rename-variable',
    title: 'Rename Variable',
    description: 'Change the variable name from "tmp" to "result".',
    initialBuffer: ['const tmp = calculate();', 'return tmp;'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['const result = calculate();', 'return result;'],
    hints: ['Use ciw to change each occurrence', 'Navigate with / or just w movements'],
    optimalKeystrokes: 18, // Multiple ciw operations
    category: 'challenge',
    difficulty: 'intermediate',
  },
  {
    id: 'challenge-swap-lines',
    title: 'Swap Two Lines',
    description: 'Swap the order of the two variable declarations.',
    initialBuffer: ['const b = 2;', 'const a = 1;'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['const a = 1;', 'const b = 2;'],
    hints: ['Delete a line with dd, move, and put with p or P'],
    optimalKeystrokes: 3, // ddp
    category: 'challenge',
    difficulty: 'beginner',
  },
  {
    id: 'challenge-change-string',
    title: 'Change String Content',
    description: 'Change the greeting message.',
    initialBuffer: ['const greeting = "Hello, World!";'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['const greeting = "Hi there!";'],
    hints: ['Navigate inside the quotes and use ci"'],
    optimalKeystrokes: 14, // f"ci"Hi there!<Esc>
    category: 'challenge',
    difficulty: 'intermediate',
  },
  {
    id: 'challenge-extract-value',
    title: 'Extract Object Value',
    description: 'Delete everything except the value 42.',
    initialBuffer: ['const config = { value: 42, extra: true };'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['42'],
    hints: ['Navigate and delete strategically', 'Could use f4 then d0 and D'],
    optimalKeystrokes: 6,
    category: 'challenge',
    difficulty: 'advanced',
  },
  {
    id: 'challenge-duplicate-modify',
    title: 'Duplicate and Modify',
    description: 'Duplicate the line and change the number.',
    initialBuffer: ['const item1 = "first";'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['const item1 = "first";', 'const item2 = "second";'],
    hints: ['Use yy p to duplicate, then navigate and change'],
    optimalKeystrokes: 15,
    category: 'challenge',
    difficulty: 'intermediate',
  },
  {
    id: 'challenge-clean-whitespace',
    title: 'Clean Up Line',
    description: 'Remove the extra spaces in the assignment.',
    initialBuffer: ['const   x   =   42;'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['const x = 42;'],
    hints: ['Navigate to extra spaces and delete them', 'Use x to delete individual characters'],
    optimalKeystrokes: 8,
    category: 'challenge',
    difficulty: 'intermediate',
  },
  {
    id: 'challenge-wrap-in-function',
    title: 'Add Function Call',
    description: 'Wrap the number in a parseInt() call.',
    initialBuffer: ['const num = "42";'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['const num = parseInt("42");'],
    hints: ['Navigate before the string, add text, navigate to end, add )'],
    optimalKeystrokes: 15,
    category: 'challenge',
    difficulty: 'advanced',
  },
  {
    id: 'challenge-delete-block',
    title: 'Delete Code Block',
    description: 'Delete the if statement body.',
    initialBuffer: [
      'if (condition) {',
      '  doSomething();',
      '  doMore();',
      '}',
    ],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: [
      'if (condition) {',
      '}',
    ],
    hints: ['Navigate inside and delete lines with dd', 'Use j to move down, then 2dd'],
    optimalKeystrokes: 4, // j2dd
    category: 'challenge',
    difficulty: 'intermediate',
  },
];
