import { Exercise } from './types.ts';

export const commandExercises: Exercise[] = [
  // Delete commands - x, dd, D
  {
    id: 'cmd-x-basic',
    title: 'Delete Character (x)',
    description: 'Use x to delete the character under the cursor.',
    initialBuffer: ['Helllo, world!'],
    initialCursor: { line: 0, col: 3 },
    targetBuffer: ['Hello, world!'],
    hints: ['Press x to delete the character at the cursor', 'The cursor stays in place'],
    optimalKeystrokes: 1,
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-dd-basic',
    title: 'Delete Line (dd)',
    description: 'Use dd to delete the entire current line.',
    initialBuffer: ['Keep this line', 'Delete this line', 'Keep this line too'],
    initialCursor: { line: 1, col: 0 },
    targetBuffer: ['Keep this line', 'Keep this line too'],
    hints: ['Press dd to delete the whole line', 'The deleted line goes into the register'],
    optimalKeystrokes: 2,
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-D-basic',
    title: 'Delete to End (D)',
    description: 'Use D to delete from cursor to end of line.',
    initialBuffer: ['const x = 42; // remove this comment'],
    initialCursor: { line: 0, col: 13 },
    targetBuffer: ['const x = 42;'],
    hints: ['Press D to delete to end of line', 'D is equivalent to d$'],
    optimalKeystrokes: 1,
    category: 'command',
    difficulty: 'beginner',
  },

  // Delete with motions
  {
    id: 'cmd-dw-basic',
    title: 'Delete Word (dw)',
    description: 'Use dw to delete from cursor to start of next word.',
    initialBuffer: ['Delete the extra word here'],
    initialCursor: { line: 0, col: 11 },
    targetBuffer: ['Delete the word here'],
    hints: ['Press dw to delete to next word', 'This includes trailing space'],
    optimalKeystrokes: 2,
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-de-basic',
    title: 'Delete to Word End (de)',
    description: 'Use de to delete to the end of the current word.',
    initialBuffer: ['Fix the typoooo here'],
    initialCursor: { line: 0, col: 11 },
    targetBuffer: ['Fix the typ here'],
    hints: ['Press de to delete to end of word', 'This does not include the space after'],
    optimalKeystrokes: 2,
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-d$-basic',
    title: 'Delete to Line End (d$)',
    description: 'Use d$ to delete from cursor to end of line.',
    initialBuffer: ['Keep this, delete this part'],
    initialCursor: { line: 0, col: 10 },
    targetBuffer: ['Keep this,'],
    hints: ['Press d$ to delete to end of line', 'You can also use D as a shortcut'],
    optimalKeystrokes: 2,
    category: 'command',
    difficulty: 'beginner',
  },

  // Delete with text objects
  {
    id: 'cmd-diw-basic',
    title: 'Delete Inner Word (diw)',
    description: 'Use diw to delete the word under the cursor.',
    initialBuffer: ['Delete the middle word'],
    initialCursor: { line: 0, col: 13 },
    targetBuffer: ['Delete the  word'],
    hints: ['Press diw to delete inner word', 'Cursor can be anywhere in the word'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-daw-basic',
    title: 'Delete Around Word (daw)',
    description: 'Use daw to delete the word and surrounding space.',
    initialBuffer: ['Delete the middle word'],
    initialCursor: { line: 0, col: 13 },
    targetBuffer: ['Delete the word'],
    hints: ['Press daw to delete around word', 'This includes surrounding whitespace'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-di-quote',
    title: 'Delete Inside Quotes (di")',
    description: 'Use di" to delete text inside double quotes.',
    initialBuffer: ['const msg = "Hello, world!";'],
    initialCursor: { line: 0, col: 15 },
    targetBuffer: ['const msg = "";'],
    hints: ['Press di" to delete inside quotes', 'Cursor can be anywhere between quotes'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-da-paren',
    title: 'Delete Around Parens (da()',
    description: 'Use da( to delete text including parentheses.',
    initialBuffer: ['calculate(x + y)'],
    initialCursor: { line: 0, col: 12 },
    targetBuffer: ['calculate'],
    hints: ['Press da( to delete around parentheses', 'This includes the ( and )'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'intermediate',
  },

  // Change commands
  {
    id: 'cmd-cw-basic',
    title: 'Change Word (cw)',
    description: 'Use cw to change a word (delete and enter insert mode).',
    initialBuffer: ['const oldName = 42;'],
    initialCursor: { line: 0, col: 6 },
    targetBuffer: ['const newName = 42;'],
    hints: ['Press cw, type new text, press Escape', 'cw deletes to word end and enters insert mode'],
    optimalKeystrokes: 11, // cw + newName + Esc
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-ciw-basic',
    title: 'Change Inner Word (ciw)',
    description: 'Use ciw to change the entire word under cursor.',
    initialBuffer: ['Hello, world!'],
    initialCursor: { line: 0, col: 8 },
    targetBuffer: ['Hello, everyone!'],
    hints: ['Press ciw to change the word', 'Cursor can be anywhere in the word'],
    optimalKeystrokes: 12, // ciw + everyone + Esc
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-ci-quote',
    title: 'Change Inside Quotes (ci")',
    description: 'Use ci" to change text inside quotes.',
    initialBuffer: ['const name = "oldValue";'],
    initialCursor: { line: 0, col: 16 },
    targetBuffer: ['const name = "newValue";'],
    hints: ['Press ci" to change inside quotes', 'Type the new value and press Escape'],
    optimalKeystrokes: 12, // ci" + newValue + Esc
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-cc-basic',
    title: 'Change Line (cc)',
    description: 'Use cc to change the entire line.',
    initialBuffer: ['// Old comment', 'const x = 1;'],
    initialCursor: { line: 0, col: 3 },
    targetBuffer: ['// New comment', 'const x = 1;'],
    hints: ['Press cc to change the whole line', 'Type the new content and press Escape'],
    optimalKeystrokes: 17, // cc + // New comment + Esc
    category: 'command',
    difficulty: 'beginner',
  },

  // Yank and put
  {
    id: 'cmd-yy-p',
    title: 'Duplicate Line (yy + p)',
    description: 'Use yy to yank a line and p to put it below.',
    initialBuffer: ['const x = 1;'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['const x = 1;', 'const x = 1;'],
    hints: ['Press yy to yank the line', 'Press p to put it below'],
    optimalKeystrokes: 3, // yyp
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-yiw-p',
    title: 'Copy Word (yiw + p)',
    description: 'Use yiw to yank a word and p to paste it.',
    initialBuffer: ['const name = name'],
    initialCursor: { line: 0, col: 6 },
    targetBuffer: ['const name = name'],
    hints: ['Press yiw to yank the word', 'Move to position and press p to paste'],
    optimalKeystrokes: 3, // Already correct, just demonstrating
    category: 'command',
    difficulty: 'intermediate',
  },

  // Replace
  {
    id: 'cmd-r-basic',
    title: 'Replace Character (r)',
    description: 'Use r{char} to replace the character under cursor.',
    initialBuffer: ['const x = 0;'],
    initialCursor: { line: 0, col: 10 },
    targetBuffer: ['const x = 1;'],
    hints: ['Press r followed by the new character', 'This replaces without entering insert mode'],
    optimalKeystrokes: 2, // r1
    category: 'command',
    difficulty: 'beginner',
  },

  // Join lines
  {
    id: 'cmd-J-basic',
    title: 'Join Lines (J)',
    description: 'Use J to join the current line with the next.',
    initialBuffer: ['Hello,', 'world!'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['Hello, world!'],
    hints: ['Press J to join lines', 'A space is added between them'],
    optimalKeystrokes: 1,
    category: 'command',
    difficulty: 'beginner',
  },

  // Combined operations
  {
    id: 'cmd-swap-words',
    title: 'Swap Two Words',
    description: 'Delete a word and put it in a new position.',
    initialBuffer: ['world hello'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['hello world'],
    hints: ['Try daw to delete "world ", then move and P to put before'],
    optimalKeystrokes: 6, // dawwP
    category: 'command',
    difficulty: 'advanced',
  },
  {
    id: 'cmd-delete-inside-brackets',
    title: 'Clear Function Args',
    description: 'Delete all arguments inside the parentheses.',
    initialBuffer: ['function(arg1, arg2, arg3)'],
    initialCursor: { line: 0, col: 12 },
    targetBuffer: ['function()'],
    hints: ['Use di( to delete inside parentheses'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'intermediate',
  },

  // ==========================================
  // COPY/PASTE EXERCISES
  // ==========================================

  {
    id: 'cmd-yy-p-duplicate',
    title: 'Duplicate Line Below',
    description: 'Copy the current line and paste it below.',
    initialBuffer: ['console.log("hello");'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['console.log("hello");', 'console.log("hello");'],
    hints: ['Press yy to yank the line', 'Press p to put below'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-yy-P-above',
    title: 'Duplicate Line Above',
    description: 'Copy the current line and paste it above.',
    initialBuffer: ['const result = calculate();'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['const result = calculate();', 'const result = calculate();'],
    hints: ['Press yy to yank the line', 'Press P to put above'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-yw-paste',
    title: 'Copy Word and Paste',
    description: 'Copy the word "data" and paste it to complete the variable.',
    initialBuffer: ['const data = ;', 'let result = data;'],
    initialCursor: { line: 1, col: 13 },
    targetBuffer: ['const data = data;', 'let result = data;'],
    hints: ['Use yw to yank word', 'Move to line 1 and use p to paste'],
    optimalKeystrokes: 6,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-yiw-paste',
    title: 'Copy Inner Word',
    description: 'Copy the word under cursor using yiw and paste it.',
    initialBuffer: ['const name = "value"', 'const copy = ""'],
    initialCursor: { line: 0, col: 16 },
    targetBuffer: ['const name = "value"', 'const copy = "value"'],
    hints: ['Use yiw to yank inner word (cursor can be anywhere in word)', 'Navigate and paste with p'],
    optimalKeystrokes: 8,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-yi-quote-paste',
    title: 'Copy Inside Quotes',
    description: 'Copy text inside quotes and paste elsewhere.',
    initialBuffer: ['const src = "hello world"', 'const dest = ""'],
    initialCursor: { line: 0, col: 15 },
    targetBuffer: ['const src = "hello world"', 'const dest = "hello world"'],
    hints: ['Use yi" to yank inside quotes', 'Move to destination and paste'],
    optimalKeystrokes: 8,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-y$-paste',
    title: 'Copy to End of Line',
    description: 'Copy from cursor to end of line and paste on a new line.',
    initialBuffer: ['const x = getValue();', ''],
    initialCursor: { line: 0, col: 10 },
    targetBuffer: ['const x = getValue();', 'getValue();'],
    hints: ['Use y$ to yank to end of line', 'Move to next line and paste'],
    optimalKeystrokes: 4,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-2yy-paste',
    title: 'Copy Multiple Lines',
    description: 'Copy 2 lines and paste them below.',
    initialBuffer: ['line 1', 'line 2', 'line 3'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['line 1', 'line 2', 'line 1', 'line 2', 'line 3'],
    hints: ['Use 2yy to yank 2 lines', 'Move down and press p'],
    optimalKeystrokes: 5,
    category: 'command',
    difficulty: 'intermediate',
  },

  // ==========================================
  // DELETE BLOCK/LINE EXERCISES
  // ==========================================

  {
    id: 'cmd-2dd-delete',
    title: 'Delete Multiple Lines (2dd)',
    description: 'Delete 2 lines at once using a count.',
    initialBuffer: ['keep this', 'delete this', 'delete this too', 'keep this'],
    initialCursor: { line: 1, col: 0 },
    targetBuffer: ['keep this', 'keep this'],
    hints: ['Use 2dd to delete 2 lines at once'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-3dd-delete',
    title: 'Delete Three Lines (3dd)',
    description: 'Delete 3 lines using count prefix.',
    initialBuffer: ['header', 'remove 1', 'remove 2', 'remove 3', 'footer'],
    initialCursor: { line: 1, col: 0 },
    targetBuffer: ['header', 'footer'],
    hints: ['Use 3dd to delete 3 lines'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-di-curly',
    title: 'Delete Inside Curly Braces',
    description: 'Delete everything inside the curly braces.',
    initialBuffer: ['function test() {', '  const x = 1;', '  return x;', '}'],
    initialCursor: { line: 1, col: 5 },
    targetBuffer: ['function test() {', '}'],
    hints: ['Use di{ to delete inside curly braces'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-da-curly',
    title: 'Delete Around Curly Braces',
    description: 'Delete the curly braces and their contents.',
    initialBuffer: ['const obj = { key: "value" };'],
    initialCursor: { line: 0, col: 15 },
    targetBuffer: ['const obj = ;'],
    hints: ['Use da{ to delete around curly braces (including braces)'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-di-bracket',
    title: 'Delete Inside Square Brackets',
    description: 'Clear the array contents.',
    initialBuffer: ['const arr = [1, 2, 3, 4, 5];'],
    initialCursor: { line: 0, col: 15 },
    targetBuffer: ['const arr = [];'],
    hints: ['Use di[ to delete inside square brackets'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-da-bracket',
    title: 'Delete Array Entirely',
    description: 'Delete the entire array including brackets.',
    initialBuffer: ['const data = [1, 2, 3];'],
    initialCursor: { line: 0, col: 15 },
    targetBuffer: ['const data = ;'],
    hints: ['Use da[ to delete around square brackets'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-di-single-quote',
    title: 'Delete Inside Single Quotes',
    description: 'Clear the string inside single quotes.',
    initialBuffer: ["const name = 'John Doe';"],
    initialCursor: { line: 0, col: 16 },
    targetBuffer: ["const name = '';"],
    hints: ["Use di' to delete inside single quotes"],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-d2w-delete',
    title: 'Delete Two Words',
    description: 'Delete two words using count with motion.',
    initialBuffer: ['remove these two words here'],
    initialCursor: { line: 0, col: 7 },
    targetBuffer: ['remove words here'],
    hints: ['Use d2w to delete 2 words'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-d0-delete',
    title: 'Delete to Line Start',
    description: 'Delete from cursor to beginning of line.',
    initialBuffer: ['    const x = 42;'],
    initialCursor: { line: 0, col: 10 },
    targetBuffer: ['x = 42;'],
    hints: ['Use d0 to delete to line start'],
    optimalKeystrokes: 2,
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-dgg-delete',
    title: 'Delete to File Start',
    description: 'Delete from current line to the start of file.',
    initialBuffer: ['line 1', 'line 2', 'line 3', 'keep this'],
    initialCursor: { line: 2, col: 0 },
    targetBuffer: ['keep this'],
    hints: ['Use dgg to delete to file start'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-dG-delete',
    title: 'Delete to File End',
    description: 'Delete from current line to end of file.',
    initialBuffer: ['keep this', 'delete 1', 'delete 2', 'delete 3'],
    initialCursor: { line: 1, col: 0 },
    targetBuffer: ['keep this'],
    hints: ['Use dG to delete to file end'],
    optimalKeystrokes: 2,
    category: 'command',
    difficulty: 'intermediate',
  },

  // ==========================================
  // ADVANCED TEXT OBJECT EXERCISES
  // ==========================================

  {
    id: 'cmd-ci-paren',
    title: 'Change Inside Parentheses',
    description: 'Change the function arguments.',
    initialBuffer: ['calculate(oldArg1, oldArg2)'],
    initialCursor: { line: 0, col: 12 },
    targetBuffer: ['calculate(x, y)'],
    hints: ['Use ci( to change inside parentheses', 'Type new args and press Escape'],
    optimalKeystrokes: 8,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-ci-curly',
    title: 'Change Inside Curly Braces',
    description: 'Replace the object contents.',
    initialBuffer: ['const obj = { old: "data" };'],
    initialCursor: { line: 0, col: 16 },
    targetBuffer: ['const obj = { new: 1 };'],
    hints: ['Use ci{ to change inside braces'],
    optimalKeystrokes: 11,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-ca-quote',
    title: 'Change Around Quotes',
    description: 'Change the entire quoted string including quotes.',
    initialBuffer: ['const s = "old string";'],
    initialCursor: { line: 0, col: 12 },
    targetBuffer: ["const s = 'new';"],
    hints: ['Use ca" to change around quotes (includes quotes)'],
    optimalKeystrokes: 9,
    category: 'command',
    difficulty: 'advanced',
  },
  {
    id: 'cmd-yi-curly',
    title: 'Yank Inside Curly Braces',
    description: 'Copy object contents and paste to another object.',
    initialBuffer: ['const a = { x: 1 };', 'const b = {};'],
    initialCursor: { line: 0, col: 13 },
    targetBuffer: ['const a = { x: 1 };', 'const b = { x: 1 };'],
    hints: ['Use yi{ to yank inside braces', 'Navigate and paste'],
    optimalKeystrokes: 9,
    category: 'command',
    difficulty: 'advanced',
  },
  {
    id: 'cmd-di-tag',
    title: 'Delete Inside HTML Tag',
    description: 'Delete the content inside the div tags.',
    initialBuffer: ['<div>Remove this content</div>'],
    initialCursor: { line: 0, col: 8 },
    targetBuffer: ['<div></div>'],
    hints: ['Use dit to delete inside tag'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'advanced',
  },
  {
    id: 'cmd-cit-tag',
    title: 'Change Inside HTML Tag',
    description: 'Change the content inside the span tag.',
    initialBuffer: ['<span>old text</span>'],
    initialCursor: { line: 0, col: 8 },
    targetBuffer: ['<span>new</span>'],
    hints: ['Use cit to change inside tag'],
    optimalKeystrokes: 7,
    category: 'command',
    difficulty: 'advanced',
  },
  {
    id: 'cmd-dap',
    title: 'Delete Paragraph',
    description: 'Delete the entire paragraph.',
    initialBuffer: ['First paragraph.', '', 'Delete this', 'entire paragraph.', '', 'Keep this.'],
    initialCursor: { line: 2, col: 0 },
    targetBuffer: ['First paragraph.', '', 'Keep this.'],
    hints: ['Use dap to delete around paragraph'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'advanced',
  },

  // ==========================================
  // CUT AND MOVE EXERCISES
  // ==========================================

  {
    id: 'cmd-dd-p-move-line',
    title: 'Move Line Down',
    description: 'Cut the current line and paste it below the next line.',
    initialBuffer: ['line 3', 'line 1', 'line 2'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['line 1', 'line 2', 'line 3'],
    hints: ['Use dd to cut, j to move down, p to paste'],
    optimalKeystrokes: 4,
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-dd-P-move-up',
    title: 'Move Line Up',
    description: 'Cut the current line and paste it above.',
    initialBuffer: ['line 2', 'line 3', 'line 1'],
    initialCursor: { line: 2, col: 0 },
    targetBuffer: ['line 1', 'line 2', 'line 3'],
    hints: ['Use dd to cut, move up with k, P to paste above'],
    optimalKeystrokes: 5,
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-daw-move',
    title: 'Move Word',
    description: 'Move the word "world" to the end.',
    initialBuffer: ['hello world there'],
    initialCursor: { line: 0, col: 6 },
    targetBuffer: ['hello there world'],
    hints: ['Use daw to delete around word', 'Move to end and paste with p'],
    optimalKeystrokes: 6,
    category: 'command',
    difficulty: 'intermediate',
  },
  {
    id: 'cmd-xp-swap',
    title: 'Swap Characters',
    description: 'Fix the typo by swapping two characters.',
    initialBuffer: ['teh quick brown fox'],
    initialCursor: { line: 0, col: 1 },
    targetBuffer: ['the quick brown fox'],
    hints: ['Use xp to swap character with the next one'],
    optimalKeystrokes: 2,
    category: 'command',
    difficulty: 'beginner',
  },
  {
    id: 'cmd-deep-swap',
    title: 'Swap Words with ddp',
    description: 'Swap the order of two lines.',
    initialBuffer: ['second line', 'first line'],
    initialCursor: { line: 0, col: 0 },
    targetBuffer: ['first line', 'second line'],
    hints: ['Use ddp to swap current line with next'],
    optimalKeystrokes: 3,
    category: 'command',
    difficulty: 'beginner',
  },
];
